from __future__ import annotations

from typing import Any


def build_implementation_wave_plan(interface_ready: bool, routing_ready: bool, dff_binding_complete: bool) -> dict[str, Any]:
    rows = [
        {
            "wave_id": "Wave0",
            "module": "Approved primitive input gate",
            "reason": "lock reusable primitive root, interface audit, and routing contract",
            "dependency_modules": "",
            "approved_children_complete": True,
            "source_topology_complete": True,
            "parameter_resolution_complete": True,
            "interface_compatible": interface_ready,
            "routing_backend_ready": routing_ready,
            "generator_work_required": False,
            "expected_human_review": False,
            "entry_gate": "M12C3A4R passed",
            "exit_gate": "M12C4 planning contracts locked",
            "next_wave_dependency": "Wave1",
        },
        {
            "wave_id": "Wave1",
            "module": "DFF",
            "reason": "first dependency-closed smoke composite using approved PINV and Transmission Gate only",
            "dependency_modules": "PINV|TRANSMISSION_GATE",
            "approved_children_complete": dff_binding_complete,
            "source_topology_complete": True,
            "parameter_resolution_complete": True,
            "interface_compatible": interface_ready,
            "routing_backend_ready": routing_ready,
            "generator_work_required": True,
            "expected_human_review": True,
            "entry_gate": "DFF contract locked",
            "exit_gate": "single DFF smoke GDS + DRC + human review",
            "next_wave_dependency": "Wave2",
        },
        {
            "wave_id": "Wave2",
            "module": "PNAND2/PNAND3 and AND2/AND3",
            "reason": "requires NAND primitive generation path closure",
            "dependency_modules": "PINV|PNAND2|PNAND3",
            "approved_children_complete": False,
            "source_topology_complete": True,
            "parameter_resolution_complete": False,
            "interface_compatible": interface_ready,
            "routing_backend_ready": routing_ready,
            "generator_work_required": True,
            "expected_human_review": True,
            "entry_gate": "Wave1 closed",
            "exit_gate": "qualified NAND and AND composites",
            "next_wave_dependency": "Wave3",
        },
        {
            "wave_id": "Wave3",
            "module": "DFF_BUF, delay_chain, pdrive family",
            "reason": "composite chains after DFF and routing proof",
            "dependency_modules": "DFF|PINV",
            "approved_children_complete": dff_binding_complete,
            "source_topology_complete": True,
            "parameter_resolution_complete": True,
            "interface_compatible": interface_ready,
            "routing_backend_ready": routing_ready,
            "generator_work_required": True,
            "expected_human_review": True,
            "entry_gate": "Wave1 closed",
            "exit_gate": "buffer and delay-chain composites qualified",
            "next_wave_dependency": "Wave4",
        },
        {
            "wave_id": "Wave4",
            "module": "ADDR_DFF / DATA_DFF",
            "reason": "array-style hierarchical composition after DFF proof",
            "dependency_modules": "DFF",
            "approved_children_complete": dff_binding_complete,
            "source_topology_complete": True,
            "parameter_resolution_complete": True,
            "interface_compatible": interface_ready,
            "routing_backend_ready": routing_ready,
            "generator_work_required": True,
            "expected_human_review": True,
            "entry_gate": "Wave1 closed",
            "exit_gate": "qualified DFF row arrays",
            "next_wave_dependency": "Wave5",
        },
        {
            "wave_id": "Wave5",
            "module": "TIME",
            "reason": "full control region composition only after all child composites qualify",
            "dependency_modules": "ADDR_DFF|DATA_DFF|DFF_BUF|AND2|AND3|delay_chain|pdrive|wl_pdrive|pdrive2_for_pre",
            "approved_children_complete": False,
            "source_topology_complete": True,
            "parameter_resolution_complete": True,
            "interface_compatible": interface_ready,
            "routing_backend_ready": routing_ready,
            "generator_work_required": True,
            "expected_human_review": True,
            "entry_gate": "Waves 1-4 closed",
            "exit_gate": "TIME region qualified",
            "next_wave_dependency": "",
        },
    ]
    return {
        "rows": rows,
        "implementation_wave_plan_locked": True,
        "first_implementation_wave": "Wave1",
        "first_implementation_module": "DFF",
    }
