from __future__ import annotations

from pathlib import Path
from typing import Any


DEVICE_FIELDS = [
    "name",
    "original_classification",
    "corrected_classification",
    "source_evidence",
    "requires_standalone_gds",
    "requires_pdk_device_generator",
    "counts_as_missing_control_module",
    "recommended_physical_handling",
]

ALIAS_FIELDS = [
    "logical_name",
    "source_class",
    "source_instance_path",
    "logical_alias_group",
    "nmos_width",
    "pmos_width",
    "length",
    "drive_scale",
    "other_parameters",
    "expected_pin_order",
    "candidate_gds_path",
    "candidate_cell_name",
    "candidate_geometry_fingerprint",
    "candidate_parameter_trace",
    "candidate_fixed_or_parameterized",
    "exact_parameter_match",
    "pin_match",
    "rail_match",
    "can_share_same_physical_cell",
    "requires_distinct_physical_variant",
    "qualification_status",
    "rejection_reason",
]


def build_device_model_reclassification() -> dict[str, Any]:
    rows = [
        {
            "name": "NMOS_VTG",
            "original_classification": "MISSING_CONTROL_MODULE",
            "corrected_classification": "PDK_DEVICE_MODEL_REFERENCE",
            "source_evidence": "OpenYield TIME and standard-cell sources use NMOS_VTG as the SPICE model name on transistor instances, not as a placeable GDS hardmacro.",
            "requires_standalone_gds": False,
            "requires_pdk_device_generator": True,
            "counts_as_missing_control_module": False,
            "recommended_physical_handling": "Treat as technology-device model input; satisfy through transistor primitive generator or PDK-backed leaf generation, not by searching for a standalone CONTROL_LOGIC hardmacro.",
        },
        {
            "name": "PMOS_VTG",
            "original_classification": "MISSING_CONTROL_MODULE",
            "corrected_classification": "PDK_DEVICE_MODEL_REFERENCE",
            "source_evidence": "OpenYield TIME and standard-cell sources use PMOS_VTG as the SPICE model name on transistor instances, not as a placeable GDS hardmacro.",
            "requires_standalone_gds": False,
            "requires_pdk_device_generator": True,
            "counts_as_missing_control_module": False,
            "recommended_physical_handling": "Treat as technology-device model input; satisfy through transistor primitive generator or PDK-backed leaf generation, not by searching for a standalone CONTROL_LOGIC hardmacro.",
        },
    ]
    return {
        "rows": rows,
        "fields": DEVICE_FIELDS,
        "device_model_reclassification_completed": True,
        "device_model_reference_count": 2,
        "device_models_removed_from_missing_hardmacro_count": 2,
    }


def build_alias_variant_matrix(mapping_rows: list[dict[str, str]], inventory: dict[str, Any]) -> dict[str, Any]:
    path_by_module = {row["logical_module"]: row["existing_openyield_gds_path"] for row in mapping_rows}
    fingerprint_by_path: dict[str, str] = {}
    for row in inventory["inventory_rows"]:
        if row["top_cell"] and row["gds_path"] not in fingerprint_by_path:
            fingerprint_by_path[row["gds_path"]] = row["source_commit_or_hash"][:16]
    rows = [
        {
            "logical_name": "PINV",
            "source_class": "Pinv",
            "source_instance_path": "AND2.inv_driver",
            "logical_alias_group": "PINV_ALIAS",
            "nmos_width": "0.09e-6",
            "pmos_width": "0.27e-6",
            "length": "0.05e-6",
            "drive_scale": "1",
            "other_parameters": "fixed inverter in AND2/AND3 support logic",
            "expected_pin_order": "VDD|VSS|A|Z",
            "candidate_gds_path": path_by_module.get("PINV", ""),
            "candidate_cell_name": "gen_inv",
            "candidate_geometry_fingerprint": fingerprint_by_path.get(path_by_module.get("PINV", ""), ""),
            "candidate_parameter_trace": "layoutgen gen_inv is a fixed inverter leaf; no explicit OpenYield width trace is embedded in GDS metadata",
            "candidate_fixed_or_parameterized": "FIXED_ONLY",
            "exact_parameter_match": True,
            "pin_match": False,
            "rail_match": False,
            "can_share_same_physical_cell": True,
            "requires_distinct_physical_variant": False,
            "qualification_status": "QUALIFIED_REFERENCE_ONLY",
            "rejection_reason": "",
        },
        {
            "logical_name": "PINV1",
            "source_class": "Pinv",
            "source_instance_path": "DFF.inv_dff",
            "logical_alias_group": "PINV_ALIAS",
            "nmos_width": "0.25e-6",
            "pmos_width": "0.50e-6",
            "length": "0.05e-6",
            "drive_scale": "fixed",
            "other_parameters": "also reused in delay_chain and pdrive stage1 with distinct width expectations",
            "expected_pin_order": "VDD|VSS|A|Z",
            "candidate_gds_path": path_by_module.get("PINV1", ""),
            "candidate_cell_name": "gen_inv",
            "candidate_geometry_fingerprint": fingerprint_by_path.get(path_by_module.get("PINV1", ""), ""),
            "candidate_parameter_trace": "candidate mapping points to the same generic gen_inv cell used by other aliases",
            "candidate_fixed_or_parameterized": "FIXED_ONLY",
            "exact_parameter_match": False,
            "pin_match": False,
            "rail_match": False,
            "can_share_same_physical_cell": False,
            "requires_distinct_physical_variant": True,
            "qualification_status": "REJECTED_SIZE_ALIAS_COLLISION",
            "rejection_reason": "PINV1 expects larger transistor sizes than generic gen_inv and cannot share the same fixed candidate GDS with PINV/PINV_wl_en_bar.",
        },
        {
            "logical_name": "PINV2",
            "source_class": "Pinv",
            "source_instance_path": "pdrive2_for_pre.inv2",
            "logical_alias_group": "PINV_ALIAS",
            "nmos_width": "0.27e-6 * drive_scale",
            "pmos_width": "0.81e-6 * drive_scale",
            "length": "0.05e-6",
            "drive_scale": "parameterized",
            "other_parameters": "also used in wl_pdrive and DFF_BUF output buffering",
            "expected_pin_order": "VDD|VSS|A|Z",
            "candidate_gds_path": path_by_module.get("PINV2", ""),
            "candidate_cell_name": "gen_inv",
            "candidate_geometry_fingerprint": fingerprint_by_path.get(path_by_module.get("PINV2", ""), ""),
            "candidate_parameter_trace": "candidate mapping points to one fixed gen_inv leaf while OpenYield source requires scaled variants",
            "candidate_fixed_or_parameterized": "FIXED_ONLY",
            "exact_parameter_match": False,
            "pin_match": False,
            "rail_match": False,
            "can_share_same_physical_cell": False,
            "requires_distinct_physical_variant": True,
            "qualification_status": "REJECTED_SIZE_ALIAS_COLLISION",
            "rejection_reason": "PINV2 is drive-scaled or larger than the generic inverter sample.",
        },
        {
            "logical_name": "PINV3",
            "source_class": "Pinv",
            "source_instance_path": "pdrive.inv3",
            "logical_alias_group": "PINV_ALIAS",
            "nmos_width": "0.91e-6 * drive_scale^0.75",
            "pmos_width": "2.43e-6 * drive_scale^0.75",
            "length": "0.05e-6",
            "drive_scale": "parameterized",
            "other_parameters": "third stage of pdrive clock buffer chain",
            "expected_pin_order": "VDD|VSS|A|Z",
            "candidate_gds_path": path_by_module.get("PINV3", ""),
            "candidate_cell_name": "gen_inv",
            "candidate_geometry_fingerprint": fingerprint_by_path.get(path_by_module.get("PINV3", ""), ""),
            "candidate_parameter_trace": "candidate mapping points to one fixed gen_inv leaf while OpenYield source requires a much larger stage-3 variant",
            "candidate_fixed_or_parameterized": "FIXED_ONLY",
            "exact_parameter_match": False,
            "pin_match": False,
            "rail_match": False,
            "can_share_same_physical_cell": False,
            "requires_distinct_physical_variant": True,
            "qualification_status": "REJECTED_SIZE_ALIAS_COLLISION",
            "rejection_reason": "PINV3 requires a distinct large-drive physical variant.",
        },
        {
            "logical_name": "PINV4",
            "source_class": "Pinv",
            "source_instance_path": "pdrive.inv4",
            "logical_alias_group": "PINV_ALIAS",
            "nmos_width": "2.43e-6 * drive_scale",
            "pmos_width": "7.29e-6 * drive_scale",
            "length": "0.05e-6",
            "drive_scale": "parameterized",
            "other_parameters": "final stage of pdrive clock buffer chain",
            "expected_pin_order": "VDD|VSS|A|Z",
            "candidate_gds_path": path_by_module.get("PINV4", ""),
            "candidate_cell_name": "gen_inv",
            "candidate_geometry_fingerprint": fingerprint_by_path.get(path_by_module.get("PINV4", ""), ""),
            "candidate_parameter_trace": "candidate mapping points to one fixed gen_inv leaf while OpenYield source requires the largest buffer stage",
            "candidate_fixed_or_parameterized": "FIXED_ONLY",
            "exact_parameter_match": False,
            "pin_match": False,
            "rail_match": False,
            "can_share_same_physical_cell": False,
            "requires_distinct_physical_variant": True,
            "qualification_status": "REJECTED_SIZE_ALIAS_COLLISION",
            "rejection_reason": "PINV4 requires a distinct large-drive physical variant.",
        },
        {
            "logical_name": "PINV_wl_en_bar",
            "source_class": "Pinv",
            "source_instance_path": "TIME.wl_en_bar_inv",
            "logical_alias_group": "PINV_ALIAS",
            "nmos_width": "0.09e-6",
            "pmos_width": "0.27e-6",
            "length": "0.05e-6",
            "drive_scale": "1",
            "other_parameters": "wordline enable bar inverter in TIME",
            "expected_pin_order": "VDD|VSS|A|Z",
            "candidate_gds_path": path_by_module.get("PINV_wl_en_bar", ""),
            "candidate_cell_name": "gen_inv",
            "candidate_geometry_fingerprint": fingerprint_by_path.get(path_by_module.get("PINV_wl_en_bar", ""), ""),
            "candidate_parameter_trace": "same fixed physical leaf as PINV, but with a distinct logical role",
            "candidate_fixed_or_parameterized": "FIXED_ONLY",
            "exact_parameter_match": True,
            "pin_match": False,
            "rail_match": False,
            "can_share_same_physical_cell": True,
            "requires_distinct_physical_variant": False,
            "qualification_status": "QUALIFIED_REFERENCE_ONLY",
            "rejection_reason": "",
        },
        {
            "logical_name": "PNAND2",
            "source_class": "PNAND2",
            "source_instance_path": "AND2.nand_gate",
            "logical_alias_group": "NAND_ALIAS",
            "nmos_width": "0.18e-6",
            "pmos_width": "0.27e-6",
            "length": "0.05e-6",
            "drive_scale": "fixed",
            "other_parameters": "2-input NAND primitive",
            "expected_pin_order": "VDD|VSS|A|B|Z",
            "candidate_gds_path": path_by_module.get("PNAND2", ""),
            "candidate_cell_name": "gen_nand2",
            "candidate_geometry_fingerprint": fingerprint_by_path.get(path_by_module.get("PNAND2", ""), ""),
            "candidate_parameter_trace": "layoutgen gen_nand2 is a fixed NAND2 leaf; OpenYield metadata does not embed explicit width tags in GDS",
            "candidate_fixed_or_parameterized": "FIXED_ONLY",
            "exact_parameter_match": True,
            "pin_match": False,
            "rail_match": False,
            "can_share_same_physical_cell": True,
            "requires_distinct_physical_variant": False,
            "qualification_status": "QUALIFIED_REFERENCE_ONLY",
            "rejection_reason": "",
        },
        {
            "logical_name": "PNAND3",
            "source_class": "PNAND3",
            "source_instance_path": "TIME.pre_unbuf",
            "logical_alias_group": "NAND_ALIAS",
            "nmos_width": "0.27e-6",
            "pmos_width": "0.27e-6",
            "length": "0.05e-6",
            "drive_scale": "fixed",
            "other_parameters": "3-input NAND primitive",
            "expected_pin_order": "VDD|VSS|A|B|C|Z",
            "candidate_gds_path": path_by_module.get("PNAND3", ""),
            "candidate_cell_name": "gen_nand4",
            "candidate_geometry_fingerprint": fingerprint_by_path.get(path_by_module.get("PNAND3", ""), ""),
            "candidate_parameter_trace": "M12C mapped PNAND3 to gen_nand4, which is not a proven 3-input NAND implementation.",
            "candidate_fixed_or_parameterized": "FIXED_ONLY",
            "exact_parameter_match": False,
            "pin_match": False,
            "rail_match": False,
            "can_share_same_physical_cell": False,
            "requires_distinct_physical_variant": True,
            "qualification_status": "REJECTED_SOURCE_MISMATCH",
            "rejection_reason": "gen_nand4 is not source-traced as a PNAND3-equivalent cell.",
        },
    ]
    logical_alias_group_count = len({row["logical_alias_group"] for row in rows})
    physical_size_variant_count = len(
        {
            (row["logical_name"], row["nmos_width"], row["pmos_width"], row["drive_scale"])
            for row in rows
        }
    )
    exact_parameter_match_count = sum(1 for row in rows if row["exact_parameter_match"])
    size_alias_collision_count = sum(1 for row in rows if row["qualification_status"] == "REJECTED_SIZE_ALIAS_COLLISION")
    fixed_variant_only_count = sum(1 for row in rows if row["candidate_fixed_or_parameterized"] == "FIXED_ONLY")
    return {
        "rows": rows,
        "fields": ALIAS_FIELDS,
        "logical_alias_variant_analysis_completed": True,
        "logical_alias_group_count": logical_alias_group_count,
        "physical_size_variant_count": physical_size_variant_count,
        "exact_parameter_match_count": exact_parameter_match_count,
        "size_alias_collision_count": size_alias_collision_count,
        "fixed_variant_only_count": fixed_variant_only_count,
    }
