from __future__ import annotations

from pathlib import Path
from typing import Any


INVENTORY_FIELDS = [
    "source_path",
    "language",
    "class_or_function",
    "generator_scope",
    "supported_devices",
    "supported_cells",
    "technology_dependency",
    "parameter_inputs",
    "output_format",
    "uses_klayout",
    "uses_gdstk",
    "uses_openram",
    "generates_real_device_geometry",
    "generates_only_proxy_geometry",
    "pin_generation_supported",
    "rail_generation_supported",
    "contact_via_generation_supported",
    "well_implant_generation_supported",
    "parameterized_width_supported",
    "parameterized_length_supported",
    "orientation_supported",
    "source_maturity",
    "historical_usage",
    "known_drc_status",
    "reuse_feasibility",
    "recommended_role",
]


def audit_existing_layout_generators(
    *,
    repo_root: Path,
    openram_root: Path,
    openyield_root: Path,
) -> dict[str, Any]:
    rows = [
        {
            "source_path": str(openram_root / "compiler/modules/ptx.py"),
            "language": "Python",
            "class_or_function": "ptx",
            "generator_scope": "Parameterized transistor primitive",
            "supported_devices": "NMOS|PMOS",
            "supported_cells": "device primitive only",
            "technology_dependency": "OpenRAM FreePDK45 tech plugin",
            "parameter_inputs": "width|mults|tx_type|contacts|poly-connect flags",
            "output_format": "OpenRAM layout object -> GDS/SPICE",
            "uses_klayout": False,
            "uses_gdstk": False,
            "uses_openram": True,
            "generates_real_device_geometry": True,
            "generates_only_proxy_geometry": False,
            "pin_generation_supported": True,
            "rail_generation_supported": False,
            "contact_via_generation_supported": True,
            "well_implant_generation_supported": True,
            "parameterized_width_supported": True,
            "parameterized_length_supported": False,
            "orientation_supported": True,
            "source_maturity": "Production OpenRAM primitive",
            "historical_usage": "Core OpenRAM primitive generator",
            "known_drc_status": "OpenRAM-backed, not yet adapter-qualified for this project",
            "reuse_feasibility": "TRUSTED_REUSE_CANDIDATE",
            "recommended_role": "Trusted device generator backend",
        },
        {
            "source_path": str(openram_root / "compiler/base/contact.py"),
            "language": "Python",
            "class_or_function": "contact",
            "generator_scope": "Parameterized contact/via primitive",
            "supported_devices": "CONTACT|VIA stacks",
            "supported_cells": "contact arrays",
            "technology_dependency": "OpenRAM FreePDK45 tech plugin",
            "parameter_inputs": "layer_stack|dimensions|directions|implant|well",
            "output_format": "OpenRAM layout object",
            "uses_klayout": False,
            "uses_gdstk": False,
            "uses_openram": True,
            "generates_real_device_geometry": True,
            "generates_only_proxy_geometry": False,
            "pin_generation_supported": False,
            "rail_generation_supported": False,
            "contact_via_generation_supported": True,
            "well_implant_generation_supported": True,
            "parameterized_width_supported": True,
            "parameterized_length_supported": True,
            "orientation_supported": True,
            "source_maturity": "Production OpenRAM primitive",
            "historical_usage": "Core OpenRAM primitive generator",
            "known_drc_status": "OpenRAM-backed, not yet adapter-qualified for this project",
            "reuse_feasibility": "TRUSTED_REUSE_CANDIDATE",
            "recommended_role": "Trusted contact/via backend",
        },
        {
            "source_path": str(openram_root / "compiler/modules/pinv.py"),
            "language": "Python",
            "class_or_function": "pinv",
            "generator_scope": "Parameterized inverter gate",
            "supported_devices": "Uses ptx child devices",
            "supported_cells": "PINV-style inverter",
            "technology_dependency": "OpenRAM FreePDK45 tech plugin",
            "parameter_inputs": "size|beta|height|add_wells",
            "output_format": "OpenRAM layout object",
            "uses_klayout": False,
            "uses_gdstk": False,
            "uses_openram": True,
            "generates_real_device_geometry": True,
            "generates_only_proxy_geometry": False,
            "pin_generation_supported": True,
            "rail_generation_supported": True,
            "contact_via_generation_supported": True,
            "well_implant_generation_supported": True,
            "parameterized_width_supported": True,
            "parameterized_length_supported": False,
            "orientation_supported": True,
            "source_maturity": "Production OpenRAM gate primitive",
            "historical_usage": "Core OpenRAM primitive gate",
            "known_drc_status": "OpenRAM-backed, not yet adapter-qualified for this project",
            "reuse_feasibility": "TRUSTED_REUSE_CANDIDATE",
            "recommended_role": "Trusted gate generator backend for PINV family",
        },
        {
            "source_path": str(openram_root / "compiler/modules/tri_gate.py"),
            "language": "Python",
            "class_or_function": "tri_gate",
            "generator_scope": "Library wrapper",
            "supported_devices": "None directly",
            "supported_cells": "tri-state gate wrapper",
            "technology_dependency": "OpenRAM library cells",
            "parameter_inputs": "library-backed only",
            "output_format": "Wrapper/reference",
            "uses_klayout": False,
            "uses_gdstk": False,
            "uses_openram": True,
            "generates_real_device_geometry": False,
            "generates_only_proxy_geometry": False,
            "pin_generation_supported": True,
            "rail_generation_supported": True,
            "contact_via_generation_supported": False,
            "well_implant_generation_supported": False,
            "parameterized_width_supported": False,
            "parameterized_length_supported": False,
            "orientation_supported": True,
            "source_maturity": "Library wrapper",
            "historical_usage": "Reference only",
            "known_drc_status": "Depends on imported hard cells",
            "reuse_feasibility": "REFERENCE_ONLY",
            "recommended_role": "Reference for tri-state concepts, not direct primitive generator",
        },
        {
            "source_path": str(openram_root / "compiler/modules/dff.py"),
            "language": "Python",
            "class_or_function": "dff",
            "generator_scope": "Library wrapper",
            "supported_devices": "None directly",
            "supported_cells": "DFF hard-cell wrapper",
            "technology_dependency": "OpenRAM library cells",
            "parameter_inputs": "library-backed only",
            "output_format": "Wrapper/reference",
            "uses_klayout": False,
            "uses_gdstk": False,
            "uses_openram": True,
            "generates_real_device_geometry": False,
            "generates_only_proxy_geometry": False,
            "pin_generation_supported": True,
            "rail_generation_supported": True,
            "contact_via_generation_supported": False,
            "well_implant_generation_supported": False,
            "parameterized_width_supported": False,
            "parameterized_length_supported": False,
            "orientation_supported": True,
            "source_maturity": "Library wrapper",
            "historical_usage": "Reference only",
            "known_drc_status": "Depends on imported hard cells",
            "reuse_feasibility": "REFERENCE_ONLY",
            "recommended_role": "Reference for DFF interface only",
        },
        {
            "source_path": str(repo_root / "sram_layoutgen/stdcell.py"),
            "language": "Python",
            "class_or_function": "gen_inv|gen_nand2|gen_nor2|gen_dff",
            "generator_scope": "Layoutgen standard-cell proxy/golden helper",
            "supported_devices": "Abstracted gate geometry only",
            "supported_cells": "inv|nand2|nor2|dff and helpers",
            "technology_dependency": "sram_layoutgen.tech abstraction",
            "parameter_inputs": "limited sizing through local code paths",
            "output_format": "LayoutDB/GDS helper",
            "uses_klayout": False,
            "uses_gdstk": False,
            "uses_openram": False,
            "generates_real_device_geometry": False,
            "generates_only_proxy_geometry": True,
            "pin_generation_supported": True,
            "rail_generation_supported": True,
            "contact_via_generation_supported": False,
            "well_implant_generation_supported": False,
            "parameterized_width_supported": False,
            "parameterized_length_supported": False,
            "orientation_supported": True,
            "source_maturity": "Project helper",
            "historical_usage": "Golden/layoutgen reference cells",
            "known_drc_status": "Not trusted as FreePDK45 transistor-level generator",
            "reuse_feasibility": "PROXY_ONLY_DO_NOT_USE",
            "recommended_role": "Reference geometry only",
        },
        {
            "source_path": str(repo_root / "sram_layoutgen/openyield_adapter/module_gds_generators.py"),
            "language": "Python",
            "class_or_function": "module-level GDS generators",
            "generator_scope": "Candidate module export",
            "supported_devices": "Composed candidates",
            "supported_cells": "OpenYield module candidates",
            "technology_dependency": "Project-local abstractions",
            "parameter_inputs": "module-specific",
            "output_format": "GDS candidates",
            "uses_klayout": False,
            "uses_gdstk": True,
            "uses_openram": False,
            "generates_real_device_geometry": False,
            "generates_only_proxy_geometry": False,
            "pin_generation_supported": True,
            "rail_generation_supported": True,
            "contact_via_generation_supported": False,
            "well_implant_generation_supported": False,
            "parameterized_width_supported": False,
            "parameterized_length_supported": False,
            "orientation_supported": True,
            "source_maturity": "Project candidate flow",
            "historical_usage": "M11/M12 candidate generation",
            "known_drc_status": "Candidate-only",
            "reuse_feasibility": "REFERENCE_ONLY",
            "recommended_role": "Audit/reference only",
        },
        {
            "source_path": str(repo_root / "sram_layoutgen/openyield_adapter/primitive_composition_generators.py"),
            "language": "Python",
            "class_or_function": "primitive composition helpers",
            "generator_scope": "Primitive composition planning",
            "supported_devices": "Composed from candidate leaves",
            "supported_cells": "Prototype composites",
            "technology_dependency": "Project-local abstractions",
            "parameter_inputs": "composition-specific",
            "output_format": "Planning artifacts",
            "uses_klayout": False,
            "uses_gdstk": True,
            "uses_openram": False,
            "generates_real_device_geometry": False,
            "generates_only_proxy_geometry": False,
            "pin_generation_supported": True,
            "rail_generation_supported": True,
            "contact_via_generation_supported": False,
            "well_implant_generation_supported": False,
            "parameterized_width_supported": False,
            "parameterized_length_supported": False,
            "orientation_supported": True,
            "source_maturity": "Project planning helper",
            "historical_usage": "Planning only",
            "known_drc_status": "No final GDS guarantee",
            "reuse_feasibility": "REFERENCE_ONLY",
            "recommended_role": "Planning helper only",
        },
        {
            "source_path": str(repo_root / "technology/freepdk45/tech/freepdk45.lydrc"),
            "language": "Ruby/KLayout DRC",
            "class_or_function": "FreePDK45 DRC deck",
            "generator_scope": "Rule deck, not layout generation",
            "supported_devices": "N/A",
            "supported_cells": "N/A",
            "technology_dependency": "FreePDK45",
            "parameter_inputs": "input layout",
            "output_format": "KLayout DRC markers",
            "uses_klayout": True,
            "uses_gdstk": False,
            "uses_openram": False,
            "generates_real_device_geometry": False,
            "generates_only_proxy_geometry": False,
            "pin_generation_supported": False,
            "rail_generation_supported": False,
            "contact_via_generation_supported": False,
            "well_implant_generation_supported": False,
            "parameterized_width_supported": False,
            "parameterized_length_supported": False,
            "orientation_supported": False,
            "source_maturity": "Technology rule deck",
            "historical_usage": "Candidate-cell DRC in M12C2",
            "known_drc_status": "Authoritative DRC deck path exists",
            "reuse_feasibility": "REFERENCE_ONLY",
            "recommended_role": "Qualification deck only",
        },
        {
            "source_path": str(openyield_root / "sram_compiler/subcircuits/time_generate.py"),
            "language": "Python",
            "class_or_function": "TIME primitive source",
            "generator_scope": "Logical/SPICE subcircuit generation",
            "supported_devices": "PySpice netlist only",
            "supported_cells": "TIME primitives and composites",
            "technology_dependency": "OpenYield SPICE config",
            "parameter_inputs": "rows|cols|operation|device widths|length",
            "output_format": "PySpice subcircuits",
            "uses_klayout": False,
            "uses_gdstk": False,
            "uses_openram": False,
            "generates_real_device_geometry": False,
            "generates_only_proxy_geometry": False,
            "pin_generation_supported": False,
            "rail_generation_supported": False,
            "contact_via_generation_supported": False,
            "well_implant_generation_supported": False,
            "parameterized_width_supported": True,
            "parameterized_length_supported": True,
            "orientation_supported": False,
            "source_maturity": "Logical source of truth",
            "historical_usage": "M12N2/M12C hierarchy extraction",
            "known_drc_status": "No physical generator",
            "reuse_feasibility": "REFERENCE_ONLY",
            "recommended_role": "Logical primitive contract source",
        },
        {
            "source_path": str(repo_root / "scripts/M11W_wordline_driver_wrapper_pin_repair.py"),
            "language": "Python",
            "class_or_function": "wordline-driver wrapper pin repair",
            "generator_scope": "Candidate wrapper metadata repair",
            "supported_devices": "Wrapper only",
            "supported_cells": "wordline_driver wrapper",
            "technology_dependency": "Project-local metadata",
            "parameter_inputs": "wrapper metadata",
            "output_format": "GDS metadata repair outputs",
            "uses_klayout": False,
            "uses_gdstk": True,
            "uses_openram": False,
            "generates_real_device_geometry": False,
            "generates_only_proxy_geometry": False,
            "pin_generation_supported": True,
            "rail_generation_supported": True,
            "contact_via_generation_supported": False,
            "well_implant_generation_supported": False,
            "parameterized_width_supported": False,
            "parameterized_length_supported": False,
            "orientation_supported": True,
            "source_maturity": "Project repair script",
            "historical_usage": "M11W wrapper recovery",
            "known_drc_status": "Not a primitive device generator",
            "reuse_feasibility": "REFERENCE_ONLY",
            "recommended_role": "Repair evidence only",
        },
    ]
    trusted_device_rows = [row for row in rows if row["recommended_role"] == "Trusted device generator backend"]
    trusted_gate_rows = [row for row in rows if row["recommended_role"] == "Trusted gate generator backend for PINV family"]
    contact_rows = [row for row in rows if row["recommended_role"] == "Trusted contact/via backend"]
    return {
        "rows": rows,
        "fields": INVENTORY_FIELDS,
        "existing_generator_scan_completed": True,
        "existing_generator_candidate_count": len(rows),
        "trusted_device_generator_found": bool(trusted_device_rows),
        "trusted_device_generator_path": trusted_device_rows[0]["source_path"] if trusted_device_rows else "",
        "trusted_gate_generator_found": bool(trusted_gate_rows),
        "contact_via_generator_found": bool(contact_rows),
        "well_implant_generation_supported": bool(trusted_device_rows and contact_rows),
        "parameterized_width_supported": bool(trusted_device_rows),
        "parameterized_length_supported": False,
        "openram_device_generator_found": True,
        "openram_device_generator_path": str(openram_root / "compiler/modules/ptx.py"),
        "openram_generator_can_be_called_outside_openram": False,
        "openram_generator_reuse_recommended": "REUSE_AFTER_ADAPTER",
    }
