from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RejectionInfo:
    code: str
    family: str
    aliases: tuple[str, ...] = ()


REGISTRY: dict[str, RejectionInfo] = {
    "SOURCE_COMMIT_MISMATCH": RejectionInfo("SOURCE_COMMIT_MISMATCH", "SOURCE_LOCK_FAILED"),
    "SOURCE_BLOB_MISMATCH": RejectionInfo("SOURCE_BLOB_MISMATCH", "SOURCE_LOCK_FAILED"),
    "INPUT_SHA_MISMATCH": RejectionInfo("INPUT_SHA_MISMATCH", "INPUT_LOCK_FAILED"),
    "MODULE_MISSING": RejectionInfo("MODULE_MISSING", "INPUT_LOCK_FAILED"),
    "UNAPPROVED_MODULE_PRESENT": RejectionInfo("UNAPPROVED_MODULE_PRESENT", "INPUT_LOCK_FAILED"),
    "TOP_CELL_NAME_MISMATCH": RejectionInfo("TOP_CELL_NAME_MISMATCH", "PACKAGING_FAILED"),
    "DUPLICATE_TOP_CELL": RejectionInfo("DUPLICATE_TOP_CELL", "PACKAGING_FAILED"),
    "SAME_NAME_DIFFERENT_GEOMETRY": RejectionInfo("SAME_NAME_DIFFERENT_GEOMETRY", "PACKAGING_FAILED"),
    "DANGLING_REFERENCE": RejectionInfo("DANGLING_REFERENCE", "PACKAGING_FAILED"),
    "CYCLIC_REFERENCE": RejectionInfo("CYCLIC_REFERENCE", "PACKAGING_FAILED"),
    "FLATTENED_MODULE": RejectionInfo("FLATTENED_MODULE", "PACKAGING_FAILED"),
    "PACKAGED_CELL_GEOMETRY_MUTATED": RejectionInfo("PACKAGED_CELL_GEOMETRY_MUTATED", "PACKAGING_FAILED"),
    "TOP_PIN_LABEL_MISSING": RejectionInfo("TOP_PIN_LABEL_MISSING", "TOP_PIN_CONTRACT_FAILED"),
    "INTERNAL_LABEL_LEAK": RejectionInfo("INTERNAL_LABEL_LEAK", "TOP_PIN_CONTRACT_FAILED"),
    "ILLEGAL_ORIENTATION": RejectionInfo("ILLEGAL_ORIENTATION", "PLACEMENT_FAILED"),
    "ILLEGAL_ZERO_GAP_PAIR": RejectionInfo("ILLEGAL_ZERO_GAP_PAIR", "PLACEMENT_FAILED"),
    "VDD_VSS_ABUTMENT": RejectionInfo("VDD_VSS_ABUTMENT", "FOREIGN_NET_FAILED"),
    "POWER_SIGNAL_CONTACT": RejectionInfo("POWER_SIGNAL_CONTACT", "FOREIGN_NET_FAILED"),
    "CROSS_MODULE_SIGNAL_MERGE": RejectionInfo("CROSS_MODULE_SIGNAL_MERGE", "FOREIGN_NET_FAILED"),
    "PIN_ACCESS_BLOCKED": RejectionInfo("PIN_ACCESS_BLOCKED", "PIN_ACCESS_FAILED"),
    "INTER_GROUP_SPACING_INSUFFICIENT": RejectionInfo("INTER_GROUP_SPACING_INSUFFICIENT", "PLACEMENT_FAILED"),
    "MANIFEST_SHA_MISMATCH": RejectionInfo("MANIFEST_SHA_MISMATCH", "INPUT_LOCK_FAILED"),
    "MISSING_MACHINE_GATE": RejectionInfo("MISSING_MACHINE_GATE", "INPUT_LOCK_FAILED"),
    "FALSE_MACHINE_GATE_CLAIM": RejectionInfo("FALSE_MACHINE_GATE_CLAIM", "INPUT_LOCK_FAILED"),
    "WRONG_NEGATIVE_SUMMARY_BINDING": RejectionInfo("WRONG_NEGATIVE_SUMMARY_BINDING", "INPUT_LOCK_FAILED"),
    "ANNOTATION_LEAKAGE_INTO_CLEAN_ATLAS": RejectionInfo("ANNOTATION_LEAKAGE_INTO_CLEAN_ATLAS", "PACKAGING_FAILED"),
    "PNAND2_CHILD_SHA_MISMATCH": RejectionInfo("PNAND2_CHILD_SHA_MISMATCH", "STRUCTURAL_CONTRACT_FAILED"),
    "PINV_CHILD_SHA_MISMATCH": RejectionInfo("PINV_CHILD_SHA_MISMATCH", "STRUCTURAL_CONTRACT_FAILED"),
    "WRONG_PINV_VARIANT": RejectionInfo("WRONG_PINV_VARIANT", "STRUCTURAL_CONTRACT_FAILED", aliases=("STRUCTURAL_CONTRACT_FAILED",)),
    "DIRECT_TOP_LABEL_CONTRACT_FAILED": RejectionInfo("DIRECT_TOP_LABEL_CONTRACT_FAILED", "TOP_PIN_CONTRACT_FAILED"),
    "TOP_PIN_ORDER_MISMATCH": RejectionInfo("TOP_PIN_ORDER_MISMATCH", "TOP_PIN_CONTRACT_FAILED"),
    "INTERNAL_NET_EXPOSED": RejectionInfo("INTERNAL_NET_EXPOSED", "TOP_PIN_CONTRACT_FAILED"),
    "CHILD_COUNT_MISMATCH": RejectionInfo("CHILD_COUNT_MISMATCH", "STRUCTURAL_CONTRACT_FAILED"),
    "DRIVER_COUNT_MISMATCH": RejectionInfo("DRIVER_COUNT_MISMATCH", "STRUCTURAL_CONTRACT_FAILED"),
    "LOAD_COUNT_MISMATCH": RejectionInfo("LOAD_COUNT_MISMATCH", "STRUCTURAL_CONTRACT_FAILED"),
    "LOADS_PER_STAGE_MISMATCH": RejectionInfo("LOADS_PER_STAGE_MISMATCH", "STRUCTURAL_CONTRACT_FAILED"),
    "WRONG_CHILD_TYPE": RejectionInfo("WRONG_CHILD_TYPE", "STRUCTURAL_CONTRACT_FAILED"),
    "STAGE_ORDER_MISMATCH": RejectionInfo("STAGE_ORDER_MISMATCH", "STRUCTURAL_CONTRACT_FAILED", aliases=("STRUCTURAL_CONTRACT_FAILED",)),
    "STAGE_DISCONNECTED": RejectionInfo("STAGE_DISCONNECTED", "CONNECTIVITY_MISMATCH", aliases=("CONNECTIVITY_MISMATCH",)),
    "UNEXPECTED_INTERNAL_NET_MERGE": RejectionInfo("UNEXPECTED_INTERNAL_NET_MERGE", "CONNECTIVITY_MISMATCH", aliases=("CONNECTIVITY_MISMATCH",)),
    "A_Z_REVERSED": RejectionInfo("A_Z_REVERSED", "CONNECTIVITY_MISMATCH", aliases=("CONNECTIVITY_MISMATCH",)),
    "CHILD_GEOMETRY_MUTATED": RejectionInfo("CHILD_GEOMETRY_MUTATED", "CHILD_IMMUTABILITY_FAILED"),
    "PNAND2_Z_NOT_CONNECTED_TO_PINV_A": RejectionInfo("PNAND2_Z_NOT_CONNECTED_TO_PINV_A", "CONNECTIVITY_MISMATCH", aliases=("CONNECTIVITY_MISMATCH",)),
    "UNEXPECTED_NET_MERGE_ZB_INT_Z": RejectionInfo("UNEXPECTED_NET_MERGE_ZB_INT_Z", "CONNECTIVITY_MISMATCH", aliases=("CONNECTIVITY_MISMATCH",)),
    "POWER_SIGNAL_SHORT_ZB_INT_VDD": RejectionInfo("POWER_SIGNAL_SHORT_ZB_INT_VDD", "POWER_SIGNAL_SHORT", aliases=("POWER_SIGNAL_SHORT",)),
    "POWER_SIGNAL_SHORT_ZB_INT_VSS": RejectionInfo("POWER_SIGNAL_SHORT_ZB_INT_VSS", "POWER_SIGNAL_SHORT", aliases=("POWER_SIGNAL_SHORT",)),
    "VDD_VSS_SHORT": RejectionInfo("VDD_VSS_SHORT", "POWER_SIGNAL_SHORT"),
    "TOP_INPUT_BINDING_MISMATCH_A_B": RejectionInfo("TOP_INPUT_BINDING_MISMATCH_A_B", "CONNECTIVITY_MISMATCH", aliases=("CONNECTIVITY_MISMATCH",)),
    "PINV_INPUT_OUTPUT_BINDING_REVERSED": RejectionInfo("PINV_INPUT_OUTPUT_BINDING_REVERSED", "STRUCTURAL_CONTRACT_FAILED", aliases=("STRUCTURAL_CONTRACT_FAILED",)),
    "MISSING_VIA1_CONNECTIVITY_BREAK": RejectionInfo("MISSING_VIA1_CONNECTIVITY_BREAK", "CONNECTIVITY_MISMATCH", aliases=("CONNECTIVITY_MISMATCH",)),
    "FOREIGN_NET_CONTACT": RejectionInfo("FOREIGN_NET_CONTACT", "FOREIGN_NET_FAILED"),
    "OFF_GRID_GEOMETRY": RejectionInfo("OFF_GRID_GEOMETRY", "GRID_FAILED"),
    "DRC_FAILED": RejectionInfo("DRC_FAILED", "DRC_FAILED"),
    "DETERMINISM_FAILED": RejectionInfo("DETERMINISM_FAILED", "DETERMINISM_FAILED"),
    "STRUCTURAL_CONTRACT_FAILED": RejectionInfo("STRUCTURAL_CONTRACT_FAILED", "STRUCTURAL_CONTRACT_FAILED"),
    "CONNECTIVITY_MISMATCH": RejectionInfo("CONNECTIVITY_MISMATCH", "CONNECTIVITY_MISMATCH"),
    "POWER_SIGNAL_SHORT": RejectionInfo("POWER_SIGNAL_SHORT", "POWER_SIGNAL_SHORT"),
}


def rejection_family(code: str) -> str:
    info = REGISTRY.get(code)
    return info.family if info else "UNKNOWN"


def code_matches(expected_code: str, actual_code: str) -> bool:
    if expected_code == actual_code:
        return True
    expected = REGISTRY.get(expected_code)
    return actual_code in expected.aliases if expected else False
