from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
STANDALONE_ROOT = SCRIPT_DIR.parent
if str(STANDALONE_ROOT) not in sys.path:
    sys.path.insert(0, str(STANDALONE_ROOT))

from sram_layoutgen.geometry import Rect  # noqa: E402
from sram_layoutgen.standalone import StandaloneSpec, build_layout, load_bundled_freepdk45  # noqa: E402


STORAGE_ARRAY_NAMES = {"bitcell_array", "dummy_left_array", "dummy_right_array", "replica_bitline_array"}
ALLOWED_STORAGE_MACROS = {"cell_1rw", "dummy_cell_1rw", "replica_cell_1rw"}
DISALLOWED_AGGREGATION_MACROS = {
    "sense_amp",
    "write_driver",
    "dff",
    "tri_gate",
    "gen_col_mux",
    "gen_wl_driver",
    "gen_precharge",
}


@dataclass(frozen=True)
class CaseSpec:
    label: str
    word_size: int
    num_words: int
    words_per_row: int

    @property
    def rows(self) -> int:
        return self.num_words // self.words_per_row

    @property
    def cols(self) -> int:
        return self.word_size * self.words_per_row


def main() -> int:
    parser = argparse.ArgumentParser(description="Compare legacy storage placement against limited OpenYield storage aggregation.")
    parser.add_argument("--cases", nargs="+", default=["2x16_wpr1", "4x32_wpr2"])
    parser.add_argument("--out-json", default="docs/openyield_storage_aggregation_compare_report.json")
    parser.add_argument("--out-md", default="docs/openyield_storage_aggregation_compare_report.md")
    args = parser.parse_args()

    tech = load_bundled_freepdk45()
    cases = [parse_case(value) for value in args.cases]
    results = [compare_case(case, tech) for case in cases]
    report = {
        "summary": {
            "cases": [case.label for case in cases],
            "generated_gds": False,
            "gds_note": "No GDS was generated by this compare script; any future GDS from this mode is smoke output, not final signoff.",
            "routing_changed": False,
            "gds_writer_changed": False,
            "shared_rail_merge": False,
            "peripheral_aggregation": False,
            "ready_for_next_step": all(item["checks"]["clean"] for item in results),
        },
        "cases": results,
        "next_step_recommendations": [
            "Keep OpenYield aggregation behind the explicit enable flag until routing and signoff are evaluated.",
            "Investigate whether the larger audited bbox pitch is acceptable before moving from storage-only placement to any peripheral aggregation.",
            "Do not aggregate sense/write/column/wordline/DFF logic until each macro has a verified pin, rail, and semantic contract.",
        ],
    }

    out_json = resolve_output(args.out_json)
    out_md = resolve_output(args.out_md)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    out_md.write_text(format_markdown(report), encoding="utf-8")
    print(f"Wrote {out_json}")
    print(f"Wrote {out_md}")
    for item in results:
        delta = item["delta"]
        print(
            f"{item['case']}: area {item['legacy']['total']['area']} -> "
            f"{item['openyield_enabled']['total']['area']} "
            f"({delta['delta_area_percent']}%) clean={item['checks']['clean']}"
        )
    return 0


def parse_case(value: str) -> CaseSpec:
    match = re.fullmatch(r"(?P<word>\d+)x(?P<words>\d+)_wpr(?P<wpr>\d+)", value)
    if not match:
        raise ValueError(f"invalid case '{value}', expected format like 4x32_wpr2")
    return CaseSpec(
        label=value,
        word_size=int(match.group("word")),
        num_words=int(match.group("words")),
        words_per_row=int(match.group("wpr")),
    )


def compare_case(case: CaseSpec, tech: Any) -> dict[str, Any]:
    legacy = summarize_layout(case, tech, enable=False)
    enabled = summarize_layout(case, tech, enable=True)
    delta_width = enabled["total"]["width"] - legacy["total"]["width"]
    delta_height = enabled["total"]["height"] - legacy["total"]["height"]
    delta_area = enabled["total"]["area"] - legacy["total"]["area"]
    legacy_area = legacy["total"]["area"]
    delta = {
        "delta_width": rounded(delta_width),
        "delta_height": rounded(delta_height),
        "delta_area": rounded(delta_area),
        "delta_area_percent": rounded(100.0 * delta_area / legacy_area if legacy_area else 0.0),
        "bitcell_pitch_before": legacy["bitcell_pitch"],
        "bitcell_pitch_after": enabled["bitcell_pitch"],
        "storage_bbox_before": legacy["storage_bbox"],
        "storage_bbox_after": enabled["storage_bbox"],
    }
    checks = check_enabled_path(legacy, enabled)
    return {
        "case": case.label,
        "word_size": case.word_size,
        "num_words": case.num_words,
        "wpr": case.words_per_row,
        "rows": case.rows,
        "cols": case.cols,
        "legacy": legacy,
        "openyield_enabled": enabled,
        "delta": delta,
        "checks": checks,
    }


def summarize_layout(case: CaseSpec, tech: Any, *, enable: bool) -> dict[str, Any]:
    spec = StandaloneSpec(
        word_size=case.word_size,
        num_words=case.num_words,
        words_per_row=case.words_per_row,
        enable_openyield_array_aggregation=enable,
    )
    layout = build_layout(spec, tech)
    arrays_by_name = {array.name: array for array in layout.cell_arrays}
    storage_arrays = {name: arrays_by_name[name] for name in STORAGE_ARRAY_NAMES if name in arrays_by_name}
    integration = layout.metadata.get("openyield_array_aggregation_integration", {})
    total = boundary_summary(layout)
    storage_instance_count = sum(array.rows * array.columns for array in storage_arrays.values())
    peripheral_instance_count = (
        sum(array.rows * array.columns for array in layout.cell_arrays if array.name not in STORAGE_ARRAY_NAMES)
        + len(layout.instances)
    )
    aggregation_plan = integration.get("storage_plan", {}) if isinstance(integration, dict) else {}
    plan_macros = sorted(
        {
            str(plan.get("cell_macro"))
            for plan in aggregation_plan.get("plans", [])
            if isinstance(plan, dict) and plan.get("cell_macro")
        }
    )
    return {
        "enabled": enable,
        "rows": case.rows,
        "cols": case.cols,
        "wpr": case.words_per_row,
        "storage_array_macro": sorted({array.cell for array in storage_arrays.values()}),
        "bitcell_pitch": {
            "x": rounded(float(layout.metadata.get("bitcell_pitch_x_um", 0.0) or 0.0)),
            "y": rounded(float(layout.metadata.get("bitcell_pitch_y_um", 0.0) or 0.0)),
        },
        "bitcell_array_bbox": rect_dict(storage_arrays["bitcell_array"].rect),
        "dummy_array_bbox": rect_dict(Rect.union([storage_arrays["dummy_left_array"].rect, storage_arrays["dummy_right_array"].rect])),
        "replica_array_bbox": rect_dict(storage_arrays["replica_bitline_array"].rect),
        "storage_bbox": rect_dict(Rect.union(array.rect for array in storage_arrays.values())),
        "storage_arrays": {
            name: {
                "cell": array.cell,
                "rows": array.rows,
                "cols": array.columns,
                "pitch_x": rounded(array.pitch_x),
                "pitch_y": rounded(array.pitch_y),
                "mirror_x": array.mirror_x,
                "mirror_y": array.mirror_y,
                "bbox": rect_dict(array.rect),
            }
            for name, array in sorted(storage_arrays.items())
        },
        "total": total,
        "storage_instance_count": storage_instance_count,
        "peripheral_instance_count": peripheral_instance_count,
        "generated_gds": False,
        "routing_changed": bool(integration.get("routing_changed", False)) if isinstance(integration, dict) else False,
        "shared_rail_merge": bool(integration.get("shared_rail_merge", False)) if isinstance(integration, dict) else False,
        "changed_gds_flow": bool(integration.get("changed_gds_flow", False)) if isinstance(integration, dict) else False,
        "aggregation_metadata": {
            "enabled": bool(integration.get("enabled", False)) if isinstance(integration, dict) else False,
            "storage_only": bool(integration.get("storage_only", False)) if isinstance(integration, dict) else False,
            "peripherals_old_path": bool(integration.get("peripherals_old_path", False)) if isinstance(integration, dict) else False,
            "power_rail_policy": integration.get("power_rail_policy") if isinstance(integration, dict) else None,
            "plan_macros": plan_macros,
            "macro_counts": integration.get("macro_counts", {}) if isinstance(integration, dict) else {},
        },
    }


def check_enabled_path(legacy: dict[str, Any], enabled: dict[str, Any]) -> dict[str, Any]:
    plan_macros = set(enabled["aggregation_metadata"]["plan_macros"])
    disallowed = sorted(plan_macros & DISALLOWED_AGGREGATION_MACROS)
    storage_arrays = enabled["storage_arrays"]
    legacy_arrays = legacy["storage_arrays"]
    enabled_r0 = all(not item["mirror_x"] and not item["mirror_y"] for item in storage_arrays.values())
    legacy_mirror = all(item["mirror_x"] and not item["mirror_y"] for item in legacy_arrays.values())
    pitch = enabled["bitcell_pitch"]
    pitch_ok = abs(pitch["x"] - 0.895) <= 0.001 and abs(pitch["y"] - 1.565) <= 0.001
    checks = {
        "only_storage_arrays_replaced": enabled["aggregation_metadata"]["storage_only"] is True
        and enabled["aggregation_metadata"]["peripherals_old_path"] is True,
        "only_allowed_storage_macros": plan_macros <= ALLOWED_STORAGE_MACROS,
        "disallowed_peripheral_macros_in_aggregation_plan": disallowed,
        "no_disallowed_peripheral_macros_in_aggregation_plan": not disallowed,
        "routing_unchanged": enabled["routing_changed"] is False,
        "shared_rail_merge_unchanged": enabled["shared_rail_merge"] is False,
        "gds_writer_unchanged": True,
        "default_legacy_mirror_path": legacy_mirror,
        "enabled_storage_arrays_r0_no_mirror": enabled_r0,
        "enabled_pitch_matches_openyield_audit": pitch_ok,
        "generated_gds": False,
    }
    checks["clean"] = all(
        value is True
        for key, value in checks.items()
        if key not in {"disallowed_peripheral_macros_in_aggregation_plan", "generated_gds"}
    ) and checks["generated_gds"] is False
    return checks


def boundary_summary(layout: Any) -> dict[str, Any]:
    boundary = next(
        (shape.rect for shape in layout.shapes if shape.purpose == "boundary" and shape.name == "prBoundary"),
        layout.bounds,
    )
    return {
        "bbox": rect_dict(boundary),
        "width": rounded(boundary.width),
        "height": rounded(boundary.height),
        "area": rounded(boundary.area),
    }


def rect_dict(rect: Rect) -> dict[str, float]:
    return {
        "x0": rounded(rect.x0),
        "y0": rounded(rect.y0),
        "x1": rounded(rect.x1),
        "y1": rounded(rect.y1),
        "width": rounded(rect.width),
        "height": rounded(rect.height),
        "area": rounded(rect.area),
    }


def format_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# OpenYield Storage Aggregation Compare Report",
        "",
        "This report compares the legacy storage placement path with the explicitly enabled limited OpenYield storage-array aggregation path. No GDS is generated here; any later GDS from this mode should be treated as smoke output, not final signoff.",
        "",
        "## Summary",
        "",
        f"- cases: `{', '.join(report['summary']['cases'])}`",
        f"- generated GDS: `{report['summary']['generated_gds']}`",
        f"- routing changed: `{report['summary']['routing_changed']}`",
        f"- GDS writer changed: `{report['summary']['gds_writer_changed']}`",
        f"- shared rail merge: `{report['summary']['shared_rail_merge']}`",
        f"- peripheral aggregation: `{report['summary']['peripheral_aggregation']}`",
        f"- ready for next step: `{report['summary']['ready_for_next_step']}`",
        "",
        "## Area And Pitch",
        "",
        md_table(
            [
                "case",
                "rows",
                "cols",
                "legacy area",
                "enabled area",
                "delta area",
                "delta %",
                "legacy pitch",
                "enabled pitch",
            ],
            [
                [
                    item["case"],
                    item["rows"],
                    item["cols"],
                    item["legacy"]["total"]["area"],
                    item["openyield_enabled"]["total"]["area"],
                    item["delta"]["delta_area"],
                    item["delta"]["delta_area_percent"],
                    pitch_text(item["legacy"]["bitcell_pitch"]),
                    pitch_text(item["openyield_enabled"]["bitcell_pitch"]),
                ]
                for item in report["cases"]
            ],
        ),
        "",
        "## Case Details",
        "",
    ]
    for item in report["cases"]:
        lines.extend(
            [
                f"### {item['case']}",
                "",
                md_table(
                    ["mode", "total bbox", "storage bbox", "bitcell bbox", "dummy bbox", "replica bbox", "storage inst", "peripheral inst"],
                    [
                        summary_row("legacy", item["legacy"]),
                        summary_row("openyield_enabled", item["openyield_enabled"]),
                    ],
                ),
                "",
                "Checks:",
                "",
                md_table(
                    ["check", "result"],
                    [[key, value] for key, value in item["checks"].items()],
                ),
                "",
            ]
        )
    lines.extend(
        [
            "## Legacy Peripheral Path",
            "",
            "The enabled path still uses the legacy placement for sense amps, write drivers, tri-gates, column muxes, wordline drivers, precharge, DFF/control logic, and generated control logic. The aggregation plan is restricted to `cell_1rw`, `dummy_cell_1rw`, and `replica_cell_1rw`.",
            "",
            "## Next Steps",
            "",
            *[f"- {item}" for item in report["next_step_recommendations"]],
            "",
        ]
    )
    return "\n".join(lines)


def summary_row(label: str, data: dict[str, Any]) -> list[Any]:
    return [
        label,
        bbox_text(data["total"]["bbox"]),
        bbox_text(data["storage_bbox"]),
        bbox_text(data["bitcell_array_bbox"]),
        bbox_text(data["dummy_array_bbox"]),
        bbox_text(data["replica_array_bbox"]),
        data["storage_instance_count"],
        data["peripheral_instance_count"],
    ]


def pitch_text(pitch: dict[str, float]) -> str:
    return f"{pitch['x']} x {pitch['y']}"


def bbox_text(rect: dict[str, float]) -> str:
    return f"({rect['x0']}, {rect['y0']})-({rect['x1']}, {rect['y1']}); {rect['width']} x {rect['height']}"


def md_table(headers: list[str], rows: list[list[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    for row in rows:
        out.append("| " + " | ".join(str(cell).replace("|", "\\|").replace("\n", "<br>") for cell in row) + " |")
    return "\n".join(out)


def rounded(value: float) -> float:
    return round(float(value), 6)


def resolve_output(value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return STANDALONE_ROOT / path


if __name__ == "__main__":
    raise SystemExit(main())
